### ISSUE TITLE
helper functions to construct Codecs

### ISSUE THREAD

**Issue by chessai** [haskell-trasa/trasa#10]
I frequently have to look at the members of 'BodyCodec' etc. to remember what's inside it.
It might be useful to have something like

```haskell
bodyCodec :: NonEmpty MediaType -> (a -> ByteString) -> (ByteString -> Either Text a) -> BodyCodec a
bodyCodec = BodyCodec
```

That way, you don't really have to look at the inside of the data constructor; the top-level function tells you what it expects. If you guys (@mckeankylej @andrewthad) think this is a good idea, I'll go ahead and make the change. (My hope was to do this for most things in Codec)

**Comment by andrewthad** [comment]
I am fine with this change.

**Comment by chessai** [comment]
the obvious names for these are taken up by the typeclasses inside of Trasa/Codec.hs , but these typeclasses seem to not have any instances outside of that module. @mckeankylej why were these typeclasses made? Is there some API reason you envisioned? They seem to be used in trasa-reflex, but only as constraints.

**Comment by aljce** [comment]
I do not think this change is a good idea. This change is code bloat. If you need to remember what is inside `BodyCodec` just run `:t BodyCodec` or look on hackage.
Every typeclass in trasa is built around one idea, adding [implicits](http://agda.readthedocs.io/en/latest/language/implicit-arguments.html) and [subtyping](https://en.wikipedia.org/wiki/Subtyping) to trasa via [Trasa.Core.Implicit](https://github.com/haskell-trasa/trasa/blob/master/trasa/src/Trasa/Core/Implicit.hs). For instance `HasCaptureEncoding (CaptureStrategy route)` allows you to pass any capture encoding strategy that can be downcast into a `CaptureEncoding`.
