### ISSUE TITLE
use quantification instead of vinyl?

### ISSUE THREAD

**Issue by chessai** [haskell-trasa/trasa#11]

**Comment by aljce** [comment]
Sure if you want to PR go ahead, I like quantification a lot more than I like vinyl. The only thing that worries me is that it makes trasa even more obscure. Trasa is already very obscure so this isnt much of an argument.

**Comment by chessai** [comment]
vinyl >= 0.9 actually breaks trasa, so this is seeming more necessary at this point.

**Comment by chessai** [comment]
@goolord and i just did this
