### ISSUE TITLE
generateAllRoutes: a home?

### ISSUE THREAD

**Issue by chessai** [haskell-trasa/trasa#17]
In 0e80962 I have written a `generateAllRoutes` function which will create the `allRoutes :: [Constructed Route]` function which is so common to see in trasa code that uses `routerWith` (every use case I know of uses this). Every time I start a new project with trasa, I tell myself I want this function. I have it currently placed in `trasa` and not `trasa-th`, because of the commonness of this. I don't really want to have to use `trasa-th` for something so simple, since I never use trasa-th, but I have always wanted to use this (and after writing this comment I am going to, for the first time). We introduced the template-haskell and th-abstraction dependencies, but those are extremely lightweight (really only depend on boot packages).

Anyway, I intend to keep `generateAllRoutes` in Trasa.Core as a helper function unless someone prefers otherwise. So if you have thoughts, please comment them here.

**Comment by andrewthad** [comment]
I’m fine with adding this.

**Comment by chessai** [comment]
The others seem ok with this so im just going to close
