### ISSUE TITLE
add `jsonBodyCodec` and `jsonCaptureCodec` to `Trasa.Codec`?

### ISSUE THREAD

**Issue by chessai** [haskell-trasa/trasa#18]
We already have `showReadBodyCodec :: (Show a, Read a) => BodyCodec a`. If we picked up `aeson` as a dependency we could easily add `jsonBodyCodec :: (FromJSON a, ToJSON a) => BodyCodec a`, which I have defined in several projects, and which is also defined in the test suite for `trasa-client`. Additionally, I don't see any nontrivial use of `trasa` not already depending on `aeson`. Would you all be open to me adding this? For maximal clarity, the impl is:

```Haskell
jsonBodyCodec :: (FromJSOn a, ToJSON a) => BodyCodec a
jsonBodyCodec = BodyCodec 
  (pure "application/json; charset=utf-8")
  A.encode
  (first T.pack . A.eitherDecode)
```

EDIT: This also goes for `jsonCaptureCodec`.

**Comment by chessai** [comment]
note that actually, trasa already transitively depends on aeson

**Comment by chessai** [comment]
See https://github.com/haskell-trasa/trasa/pull/20

**Comment by andrewthad** [comment]
I’m fine with this being added. There are no longer any actively developed web applications using trasa, so anything that makes it easier to use is fine with me.

**Comment by chessai** [comment]
Closing this since everyone is okay with it
