### ISSUE TITLE
Raw Response

### ISSUE THREAD

**Issue by andrewthad** [haskell-trasa/trasa#2]
@mckeankylej I've got a branch `wai-raw-drew` where I've made the clarity stuff work. Crucially, `Clarity` must be defined as:

    data Clarity (r :: Type) = forall a. Clear a | Raw

We cannot have `r` inside of the `Raw` data constructor because that would imply that `Application` could live at the type level. Continuing, we rewrite `ResponseBody` as:

    data ResponseBody :: (Type -> Type) -> Clarity r -> Type where
      ResponseBodyClear :: !(f a) -> ResponseBody f (Clear a)
      ResponseBodyRaw :: !r -> ResponseBody f (Raw :: Clarity r)

This requires `TypeInType`, and it all works out (after fixing a bunch of other random stuff).

**Comment by aljce** [comment]
Aw man, I was about to do the same thing! Nice job!

**Comment by andrewthad** [comment]
I'm going to go ahead and do the necessary changes to server and client. Trying to knock out a report for **client name redacted** today, and I need to be able to stream a response.
