### ISSUE TITLE
Deprecate in favor of WASH

### ISSUE THREAD

**Issue by taktoa** [haskell-trasa/trasa#7]
@mckeankylej 
I believe [WASH](http://www2.informatik.uni-freiburg.de/~thiemann/haskell/WASH/) is a more modern solution to web authoring in Haskell. You should deprecate this library in favor of it.

**Comment by aljce** [comment]
@andrewthad @chessai I cant believe someone did type level routing better than us.

**Comment by aljce** [comment]
All in favor of a deprecation?

**Comment by andrewthad** [comment]
Hmmm... WASH *does* have  the advantage of  compatibility with GHC 6.6

**Comment by chessai** [comment]
Aye. We've had a good run.
